### ISSUE TITLE
booted bots can't join the battle

### ISSUE THREAD

**Issue by alex-314214** [robocode-dev/tank-royale#79]
1. I started robocode-tankroyale-gui-0.22.0.jar on Windows 10. 
2. Selected Config Menu -> "Bot Root Directory" and added the path to the sample bots
3. Selected Server Menu -> Start Server
4. Selected Server Menu -> Select Server -> Test  -> "server is running"
5. Selected Battle Menu -> Start Battle -> Selected some bots from "Bot Directories (local only)" and clicked on Boot-Button.
7. Selected Bots were shown on "Booted Bots (local only)" list
8. "Joined Bots (local/remote)" list stays empty. So I can't add a bot to "Selected Bots(local/remote)" list and the "Start Battle" Button remains disabled.

What wents wrong?

**Comment by flemming-n-larsen** [comment]
@alex-314214:
Thank you for sharing a description of what you do. 👍 
It looks like you did it the correct way, but I am unsure if you selected the joined bots to the battle by pressing one of the Add buttons? When you have selected which bots that must battle (in the Selected Bots (battle participants)) you should be able to press the Start Battle button.
Please notice that you will need at least two bots in the battle before the Start Battle button gets enabled.

![image](https://github.com/robocode-dev/tank-royale/assets/2179727/6ff2e3f4-49ec-4277-868e-9854cd196273)

**Comment by flemming-n-larsen** [comment]
In order to see what is going on, we need to start the bot from a terminal window.

So you should `cd` your way into the bots directory, e.g. the Corners bot, and write:

```shell
java -cp ../lib/* Corners.java
```

I expect that the Corners bot will run or write an error to standard out.

You can do the same thing for any Java bot, so if Corners works, but not your own, you should try out running your bot instead from the terminal the same way.

Please note that a server must be started in advantage.

Please note that you will run into this error:
```
Disconnected from: ws://localhost:7654, status code: 1008, reason: Invalid secret
```
This is because the server is protected with an server key that the bot needs to provide in order to connect to the server.
You can find the key in the generated `server.properties` file located at the directory where the GUI is started from.
It will look similar to this:
```
bots-secrets=ZKfl1TOEvabzxqm6YRC0og
controller-secrets=QlgOL13TnWrdQoqnKcIEpA
```
Now, before calling the `java -cp ../lib/* Corners.java` command, you should set the `SERVER_SECRET` environment variable to the secret you find in the server.properties file under `bots-secrets`.

if you use PowerShell:
```powershell
$env:SERVER_SECRET="ZKfl1TOEvabzxqm6YRC0og"
```
if you instead use Command  Prompt:
```cmd
set SERVER_SECRET=ZKfl1TOEvabzxqm6YRC0og
```
Now you should be able to connect to the server with `java -cp ../lib/* Corners.java`.

What it written out to the console in your case, when you try to start the bot?

**Comment by alex-314214** [comment]
Thank you for your hints. But I found a solution on https://github.com/robo-code/robocode/releases that works.

**Comment by flemming-n-larsen** [comment]
Anybody else encountering this issue, and what are your findings (written out by the bot(s))?

**Comment by flemming-n-larsen** [comment]
One observation on my side is, that this happens sometime when running on Linux. Hence, this needs more investigation.

**Comment by flemming-n-larsen** [comment]
Closing it for now.

**Comment by TheFlameFish** [comment]
I think I'm experiencing the same issue. When attempting to run Corners, I encounter the following error: "Error: Could not find or load main class Corners.java".

**Comment by flemming-n-larsen** [comment]
@TheFlameFish : Okay. I have now re-opened the issue.

Can you provide you with some details about your system, Java version and Robocode Tank Royale version? 🙂 
Thanks in advance.

**Comment by TheFlameFish** [comment]
Never mind, sorry, I got it working. I have Java 8 installed for a different program and apparently, it was being used as the default Java version. Changing the environment variables to have version 22 be the default fixed it.

**Comment by flemming-n-larsen** [comment]
@TheFlameFish: Thanks for the heads up.
I think I will build-in a Java version check, so an error will be thrown if the Java version is too old. Then it might get easier to figure out, that the JVM is just too old. 🙂
